name: mie429
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - black
  - black-jupyter
  - bottleneck
  - h5py
  - ipywidgets
  - isort
  - jupyter
  - matplotlib
  - numba
  - numexpr
  - optuna
  - pandas
  - pylint
  - pytorch
  - pyyaml
  - scikit-learn
  - scipy
  - tensorboard
  - torchaudio
  - torchvision
  - tqdm
